### PR TITLE
More Watershed Testing Bug fixes

### LINKED ISSUE #370: Can't reset password
Problem: When I created a new user and attempted to reset my password from the email link sent, I recieved an error message "Server Error. Failed to reset password."

Tested on Windows 10 with Chrome v70 and Apple OSX Chrome v69

Steps to recreate:
1. Log in as an admin
2. Create a user
3. click on the link to reset password sent to email address associated with new user
4. set password and re-enter the same password. I tried:
* abc123!@#
* password
* passw0rd

Expected results:
Passwords match and should be accepted into the system

Actual results:
Receive error message.
screen shot 2018-10-29 at 12 41 05 pm

### LINKED ISSUE #371: Invalid email address error
Problem: when creating a new admin in the system and I enter an invalid email address, the error message isn't very user friendly.

Steps to recreate:
1. Log in as an admin user
2. Go to manage users
3. click 'create new'
4. Enter all required fields and an invalid email address
5. Click next

Expected results:
User receives an error message "The email address entered is invalid. Please update with a valid email address to continue."

Actual results:
User receives an error message from GraphQL.
screen shot 2018-10-29 at 12 54 12 pm

### LINKED ISSUE #374: Crossings map doesn't load after adding crossing
Problem: I have recreated this twice now. When I add a crossing as an admin then click on crossings map, the page doesn't load and there is an error.

This did not happen on other occasions.

Steps to recreate:
1. Log in as an admin
2. Click on 'add crossing'
3. add data for a crossing
4. click on 'crossings map' in top navigation

Expected results:
Map loads

Actual results:
I receive a blank page and the error:
console.js:35 TypeError: t.coordinates[0].map is not a function
    at t.M.getViewportAndCenter (CrossingMapPage.js:126)
    at new t (CrossingMapPage.js:48)
    at xn (react-dom.production.min.js:150)
    at Tn (react-dom.production.min.js:162)
    at qn (react-dom.production.min.js:192)
    at Vn (react-dom.production.min.js:193)
    at er (react-dom.production.min.js:205)
    at Jn (react-dom.production.min.js:204)
    at Wn (react-dom.production.min.js:200)
    at Object.enqueueForceUpdate (react-dom.production.min.js:131)
    at l.o.forceUpdate (react.production.min.js:13)
    at l.forceRenderChildren (react-apollo.browser.umd.js:508)
    at Object.t [as next] (react-apollo.browser.umd.js:483)
    at d.next (zen-observable.js:158)
    at ObservableQuery.js:322
    at Array.forEach (<anonymous>)
    at Object.next (ObservableQuery.js:322)
    at QueryManager.js:355
    at QueryManager.js:654
    at Array.forEach (<anonymous>)
    at QueryManager.js:653
    at Map.forEach (<anonymous>)
    at e.broadcastQueries (QueryManager.js:648)
    at Object.next (QueryManager.js:682)
    at d.next (zen-observable.js:158)
    at dedupLink.js:49
    at Array.forEach (<anonymous>)
    at Object.next (dedupLink.js:49)
    at d.next (zen-observable.js:158)
    at httpLink.js:78
screen shot 2018-10-29 at 1 13 30 pm

### LINKED ISSUE #376: edit user - jurisdiction displayed incorrectly
Problem: when i edit a user, the jurisdiction assigned is not displayed properly and instead it appears that the first one in the drop down is displayed in all cases.

1. Log in as an admin
2. Click on manage users
3. drill down on a user that has a jurisdiction besides 'the city of leander'

expected results:
The jurisdiction associated with the user is displayed

actual results:
the jurisdiction field shows 'city of leander'

### LINKED ISSUE #381: create new user action - user list doesn't refresh
Problem: When you create a new user as an admin in the system, when you save and the list of users displays again, the new user is not listed until you refresh the page.

Steps to recreate:
* Log in as an admin
* Click on manage users
* Click on 'add new'
* add required fields
* click 'next'
** modal appears saying successful
* click ok to success

Expected results:
List of users displays new user

Actual results:
New user not displayed until you refresh the page

### PR DESCRIPTION
**Pull request by Niicck**
Can be viewed on our deployed dev branch: 
http://ctxfloods-frontend-dev.s3-website-us-east-1.amazonaws.com/map

- fix cloudfront invalidations
- resolve #376
- resolve #378 
- resolve #381 
- resolve #371

And these issues also shouldn't be happening:
- resolve #374
- resolve #370

### CODE REVIEW

**Comment by Niicck** [comment]
#381 broke. User list is not refreshing

File: deployment/invalidateCloudFront.js [hunk 1]
```diff
@@ -0,0 +1,33 @@
+const aws = require('aws-sdk');
+const cloudFront = new aws.CloudFront();
+
+// This function clears the cloudFront cache for production deployments.
+// Without this function, new code changes would not be implemented until the old cache expired.
+cloudFront.listDistributions({}).promise()
```
Comment (briaguya) [inline deployment/invalidateCloudFront.js]: is there a way to query for the aliases here instead of getting everything and filtering? It's not a dealbreaker for now but down the line we might end up filtering through a pretty long list.

Comment (Niicck) [reply deployment/invalidateCloudFront.js]: You can't query for aliases. As far as I know, you can only query distributions by the distribution_id, but not by the alias. And that's a route we could go for sure. My thought was that the aliases would stay the same, but I wasn't sure how/if their distribution_ids would change.
